### NumPy is the fundamental package for scientific computing with Python

In [1]:
import numpy as np

In [5]:
x = np.arange(15).reshape(3, 5)

In [7]:
# Shape of the array
x.shape

(3, 5)

In [8]:
# Number of axis in the ndarray
x.ndim

2

In [9]:
x.size

15

In [10]:
type(x)

numpy.ndarray

In [11]:
x.dtype

dtype('int32')

#### Array Creation 

In [17]:
np.zeros((2, 3, 4))

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [18]:
np.empty((2,2))

array([[  2.56761491e-312,   2.14321575e-312],
       [  2.54639495e-312,   1.16921968e-311]])

#### Create an ndarray with sequence of numbers

In [23]:
np.arange(5, 17, 2).reshape(2, 3)

array([[ 5,  7,  9],
       [11, 13, 15]])

#### Create an ndarray with sequence of floating point numbers

In [25]:
np.linspace(2, 3, 5)

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

#### Arithmetic operators (+, -, * ) performs elementwise operations. Matrix product is performed using dot

In [49]:
a = np.arange(0, 9).reshape(3,3)
b = np.arange(6, 15).reshape(3, 3)

In [50]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [52]:
a * b

array([[  0,   7,  16],
       [ 27,  40,  55],
       [ 72,  91, 112]])

In [53]:
a.dot(b)

array([[ 33,  36,  39],
       [114, 126, 138],
       [195, 216, 237]])

In [54]:
np.dot(a, b)

array([[ 33,  36,  39],
       [114, 126, 138],
       [195, 216, 237]])

#### Modifying the shape of an array
Note : Below commands returns the modified array & does not change the original array

In [55]:
# Returns flattened array
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
# Returns reshaped array
b.reshape(1,9)

array([[ 6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [58]:
# Returns transposed arrray
a.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

#### resize() modifies the array itself

In [59]:
a.resize(1, 9)

In [60]:
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [66]:
# If dimension in reshape is given as -1 then dimensions are calculated automatically
a = a.reshape(-1, 3)

In [67]:
np.concatenate((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [68]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [69]:
np.column_stack((a,b))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

#### Copy & VIew

In [79]:
# Simple assignments make no copy of array objects or their data
# Python passes mutable objects as references
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [80]:
b = a
b is a
b.shape = (2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

#### View Or Shallow Copy
Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [83]:
c = a.view()
c

array([[0, 1, 2],
       [3, 4, 5]])

In [84]:
c is a

False

In [85]:
c.base is a

True

In [86]:
c[1, 1] = 120

In [87]:
a

array([[  0,   1,   2],
       [  3, 120,   5]])

In [90]:
# Slicing of an array returns view of it
x = a[:, 1]
x[:] = 10

In [91]:
a

array([[ 0, 10,  2],
       [ 3, 10,  5]])

### Deep Copy
The copy method makes a complete copy of the array and its data

In [94]:
d = a.copy()
d

array([[ 0, 10,  2],
       [ 3, 10,  5]])

In [99]:
d[:] = 10
d

array([[10, 10, 10],
       [10, 10, 10]])

In [100]:
a

array([[ 0, 10,  2],
       [ 3, 10,  5]])